//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int StudentId { get; set; }
        public Nullable<int> P_DistrictId { get; set; }
        public string P_VillageName { get; set; }
        public string P_PostOffice { get; set; }
        public Nullable<int> T_DistrictId { get; set; }
        public string T_VillageName { get; set; }
        public string T_PostOffice { get; set; }
    
        public virtual District District { get; set; }
        public virtual District District1 { get; set; }
        public virtual Student Student { get; set; }
    }
}
