//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllMealAdmin
    {
        public int MealAdminsId { get; set; }
        public Nullable<int> MealAdminRegId { get; set; }
    
        public virtual MealAdminReg MealAdminReg { get; set; }
    }
}
