//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Communication
    {
        public int CommunicateId { get; set; }
        public string UserName { get; set; }
        public string Information { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
