//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MealAdminReg
    {
        public int MealAdminRegId { get; set; }
        public string UserName { get; set; }
        public string DepartmentName { get; set; }
        public string MobileNumber { get; set; }
        public string Name { get; set; }
        public Nullable<int> Flag { get; set; }
    
        public virtual AllMealAdmin AllMealAdmin { get; set; }
    }
}
