//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrationForm
    {
        public int RegistrationId { get; set; }
        public string UserName { get; set; }
        public string StudentName { get; set; }
        public string DeptName { get; set; }
        public string RollNumber { get; set; }
        public string Session { get; set; }
        public Nullable<int> Password { get; set; }
        public string Email { get; set; }
        public Nullable<int> IsVerified { get; set; }
        public string Verification { get; set; }
    }
}
